### PR TITLE
Tageswoche-Artikel 2016-05-03

### PR DESCRIPTION
**Pull request by dbrgn**

### CODE REVIEW

**Comment by The-Compiler** [comment]
hrmpf, I clicked "update branch" hoping I could squash-merge it via the github UI then, but nope :wink:

Do you care about the unnecessary merge commits or can I just merge this here? :laughing:

**Comment by dbrgn** [comment]
You can still squash and merge after the update :) Feel free to do it.

**Comment by dbrgn** [comment]
(Btw, I'd generally prefer squashing over a merge commit.)

**Comment by The-Compiler** [comment]
I sure can, just not via the web UI which is a bit annoying :wink:

**Comment by The-Compiler** [comment]
Okay, turns out I can't either:

```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "continuous-integration/travis-ci" is expected
To git@github.com:ccc-ch/ccc-ch.ch.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:ccc-ch/ccc-ch.ch.git'
```

I'd say either we don't care about merge commits or we turn off required status checks.

**Comment by dbrgn** [comment]
I could update and then squash & merge as usual.

Maybe you got confused because I merged another PR at the same time, so this one was outdated again :)

**Comment by dbrgn** [comment]
Deployed.

**Pull request merged**
