### PR TITLE
update urls to https in content

### PR DESCRIPTION
**Pull request by J0WI**
You may consider replacing short urls completely, I just updated them to https for now.
I didn't update urls that serve a untrusted cert, redirect back to insecure http or contain major mixed content issues.

### CODE REVIEW

**Comment by gnurbs** [comment]
@J0Wl: maybe I'm confused, but I can't remember you. Just wondering who's contributing: who are you?

**Comment by The-Compiler** [comment]
LGTM, but it seems you need to rebase to the latest master with GitHub's check enforcement turned on...

**Comment by J0WI** [comment]
I don't really understand the benefit of this, because no file conflicts and I have to do this for each PR...

**Comment by The-Compiler** [comment]
Because mandatory status checks are enabled for this repo, so GitHub won't merge things which haven't been checked in advance on Travis. I'm still all for disabling them again, but it depends on what @dbrgn thinks :wink:

**Pull request merged**
