### PR TITLE
Set up CircleCI

### PR DESCRIPTION
**Pull request by dbrgn**
Not yet ready.

### CODE REVIEW

**Comment by dbrgn** [comment]
Ok, finished and squashed. I also fixed the locale issue that we just circumvented on Travis.

Does someone want to review this?

**Comment by dbrgn** [comment]
@NiklausHofer it looks like you're not even part of the github orga yet, so I can't request a review from you. I invited you to the orga.

**Comment by NiklausHofer** [comment]
@dbrgn thx

**Comment by NiklausHofer** [comment]
Ich kenne und verwende CircleCI nicht, aber wenn du das kennst und getestet hast, habe ich kein Problem damit, das zu mergen.

**Comment by dbrgn** [comment]
Ich bin inzwischen ziemlicher Fan von CircleCI 🙂

**Pull request merged**
