### PR TITLE
Presseartikel September

### PR DESCRIPTION
**Pull request by dbrgn**

### CODE REVIEW

**Comment by dbrgn** [comment]
Rebased

**Comment by The-Compiler** [comment]
Looking at #83 we might prefer https-URLs here too?

**Comment by dbrgn** [comment]
I added https whereever it's actually supported. 

- 20min has no https at all (wrong host name)
- blick and srf redirect to http

**Comment by The-Compiler** [comment]
Okay - can you rebase again? (Or I'll just use the "Update branch" button which will do another merge commit :wink:)

**Comment by dbrgn** [comment]
Done.

**Pull request merged**
