### PR TITLE
April17 gettogether (second try)

### PR DESCRIPTION
**Pull request by NiklausHofer**
see #108 for details

### CODE REVIEW

**Comment by dbrgn** [comment]
Let's give Travis some time :) But yeah, we could temporarily disable branch protection if it doesn't work out.

**Comment by NiklausHofer** [comment]
Who is the maintainer of the Travis installation?

**Comment by dbrgn** [comment]
> Who is the maintainer of the Travis installation?

What do you mean? It's not self-hosted.

I'll try to remove and re-enable it from the repo.

**Comment by dbrgn** [comment]
> I'll try to remove and re-enable it from the repo.

Done. Maybe force-push again?

**Comment by NiklausHofer** [comment]
I think it's definitely broken...

**Comment by dbrgn** [comment]
I merged it manually :)

**Comment by dbrgn** [comment]
Deployed.

**Comment by NiklausHofer** [comment]
Danke :)

**Pull request merged**
