### PR TITLE
Pelican update

### PR DESCRIPTION
**Pull request by gnurbs**
bumps pelican to current 3.7.1. Also bumps markdown and tracks i18n_subsites

### CODE REVIEW

**Comment by gnurbs** [comment]
I'll have a look at #121, but prefer to do after this is merged, to avoid using old versions.

**Comment by gnurbs** [comment]
version check would be nice, sure!

wrt pipenv/pipfile: I use debian packages without virtualenv so far (that's how I stumbled upon this, JINJA_EXTENSIONS got removed) so I don't have an opinion here.

**Comment by dbrgn** [comment]
Ok, version check would work in any case, also for people that have an old version of Pelican installed systemwide :)

**Comment by dbrgn** [comment]
Ping @gnurbs, do you plan to add that feature in this PR?

**Comment by dbrgn** [comment]
Ping again @gnurbs.

**Pull request merged**
