### PR TITLE
add en_UK.UTF_8 to circle locales

### LINKED ISSUE #117: Fix CI
I'd suggest moving to CircleCI. I've made good experiences there.

(Maybe something I can do during 34c3)

### PR DESCRIPTION
**Pull request by gnurbs**
this would fix #117 - the "locale warning" part of it

### CODE REVIEW

**Comment by gnurbs** [comment]
Circle says:

> en_UK.UTF-8...cannot open locale definition file `en_UK': No such file or directory

do we have to touch something someplace else? I couldn't see other related config in .circleci

**Comment by dbrgn** [comment]
The english locale is `en_GB.UTF-8`, isn't it?

**Comment by gnurbs** [comment]
good point :D fixed, also in pelicanconf .

**Comment by gnurbs** [comment]
from my POV, this can be reviewed & merged

**Pull request merged**
